create type public.app_role as enum ('admin','manager', 'user');
create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references auth.users on delete cascade not null unique,
  role      app_role not null default 'user',
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create extension if not exists moddatetime schema extensions;


create trigger handle_updated_at before update on public.user_roles
  for each row execute procedure moddatetime('updated_at');



comment on table public.user_roles is 'Application roles for each user.';

-- Enable Row Level Security
alter table public.user_roles enable row level security;

-- Create policy to allow users to read their own roles
create policy "Users can view own roles"
  on public.user_roles for select
  using (auth.uid() = user_id);




-- Enable realtime for user_roles table
alter publication supabase_realtime add table public.user_roles;
